#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-Markdown
Version  : 2.6.11
Release  : 46
URL      : http://pypi.debian.net/Markdown/Markdown-2.6.11.tar.gz
Source0  : http://pypi.debian.net/Markdown/Markdown-2.6.11.tar.gz
Summary  : Python implementation of Markdown.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: deprecated-Markdown-bin = %{version}-%{release}
Requires: deprecated-Markdown-license = %{version}-%{release}
Requires: deprecated-Markdown-python = %{version}-%{release}
BuildRequires : PyYAML
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : deprecated-PyYAML-legacypython
BuildRequires : deprecated-nose-legacypython
BuildRequires : nose

%description
[Python-Markdown][]
===================
[![Build Status][travis-button]][travis]
[![Coverage Status][codecov-button]][codecov]
[![Latest Version][mdversion-button]][md-pypi]
[![Python Versions][pyversion-button]][md-pypi]
[![BSD License][bsdlicense-button]][bsdlicense]
[![Code of Conduct][codeofconduct-button]][Code of Conduct]

%package bin
Summary: bin components for the deprecated-Markdown package.
Group: Binaries
Requires: deprecated-Markdown-license = %{version}-%{release}

%description bin
bin components for the deprecated-Markdown package.


%package legacypython
Summary: legacypython components for the deprecated-Markdown package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-Markdown package.


%package license
Summary: license components for the deprecated-Markdown package.
Group: Default

%description license
license components for the deprecated-Markdown package.


%package python
Summary: python components for the deprecated-Markdown package.
Group: Default
Provides: deprecated-markdown-python

%description python
python components for the deprecated-Markdown package.


%prep
%setup -q -n Markdown-2.6.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554335666
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-Markdown
cp LICENSE.md %{buildroot}/usr/share/package-licenses/deprecated-Markdown/LICENSE.md
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/markdown_py

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-Markdown/LICENSE.md

%files python
%defattr(-,root,root,-)
